version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_HASH=${API_HASH}
      - API_ID=${API_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_CHANNEL_ID=${DB_CHANNEL_ID}
      - OWNER_ID=${OWNER_ID}
      - UPDATE_CHANNEL=${UPDATE_CHANNEL}
